const category = [
    {   id: 1,
        name: 'Category 1',
        description: 'Categoria 1',
    },
    {   id: 2,
        name: 'Category 2',
        description: 'Categoria 2',
    },
    {   id: 3,
        name: 'Category 3',
        description: 'Categoria 3',
    },
    {   id: 4,
        name: 'Category 4',
        description: 'Categoria 4',
    },
];