const products = [
    {   id: 1,
        name: 'Producto 1',
        description: 'Descripcion del producto 1',
        image: 'https://',
        ranking: 1,
        createdBy: 'admin',
        price: 100,
        category: 'Categoria 1',
        stock: 10
    },
    {   id: 2,
        name: 'Producto 2',
        description: 'Descripcion del producto 2',
        image: 'https://',
        ranking: 2,
        createdBy: 'admin',
        price: 200,
        category: 'Categoria 2',
        stock: 20
    },
    {   id: 3,
        name: 'Producto 3',
        description: 'Descripcion del producto 3',
        image: 'https://',
        ranking: 3,
        createdBy: 'admin',
        price: 300,
        category: 'Categoria 3',
        stock: 30
    },
    {   id: 4,
        name: 'Producto 4',
        description: 'Descripcion del producto 4',
        image: 'https://',
        ranking: 4,
        createdBy: 'admin',
        price: 400,
        category: 'Categoria 4',
        stock: 40
    },
    {   id: 5,
        name: 'Producto 5',
        description: 'Descripcion del producto 5',
        image: 'https://',
        ranking: 5,
        createdBy: 'admin',
        price: 500,
        category: 'Categoria 1',
        stock: 50
    },
    {   id: 6,
        name: 'Producto 6',
        description: 'Descripcion del producto 6',
        image: 'https://',
        ranking: 6,
        createdBy: 'admin',
        price: 600,
        category: 'Categoria 2',
        stock: 60
    },
    {   id: 7,
        name: 'Producto 7',
        description: 'Descripcion del producto 7',
        image: 'https://',
        ranking: 7,
        createdBy: 'admin',
        price: 700,
        category: 'Categoria 3',
        stock: 70
    },
    {   id: 8,
        name: 'Producto 8',
        description: 'Descripcion del producto 8',
        image: 'https://',
        ranking: 8,
        createdBy: 'admin',
        price: 800,
        category: 'Categoria 4',
        stock: 80
    },
    {   id: 9,
        name: 'Producto 9',
        description: 'Descripcion del producto 9',
        image: 'https://',
        ranking: 9,
        createdBy: 'admin',
        price: 900,
        category: 'Categoria 1',
        stock: 90
    },
    {   id: 10,
        name: 'Producto 10',
        description: 'Descripcion del producto 10',
        image: 'https://',
        ranking: 10,
        createdBy: 'admin',
        price: 1000,
        category: 'Categoria 2',
        stock: 100
    },
    {   id: 11,
        name: 'Producto 11',
        description: 'Descripcion del producto 11',
        image: 'https://',
        ranking: 11,
        createdBy: 'admin',
        price: 1100,
        category: 'Categoria 3',
        stock: 110
    },
    {   id: 12,
        name: 'Producto 12',
        description: 'Descripcion del producto 12',
        image: 'https://',
        ranking: 12,
        createdBy: 'admin',
        price: 1200,
        category: 'Categoria 4',
        stock: 120
    },
    {   id: 13,
        name: 'Producto 13',
        description: 'Descripcion del producto 13',
        image: 'https://',
        ranking: 13,
        createdBy: 'admin',
        price: 1300,
        category: 'Categoria 1',
        stock: 130
    },
    {   id: 14,
        name: 'Producto 14',
        description: 'Descripcion del producto 14',
        image: 'https://',
        ranking: 14,
        createdBy: 'admin',
        price: 1400,
        category: 'Categoria 2',
        stock: 140
    },
    {   id: 15,
        name: 'Producto 15',
        description: 'Descripcion del producto 15',
        image: 'https://',
        ranking: 15,
        createdBy: 'admin',
        price: 1500,
        category: 'Categoria 3',
        stock: 150
    },

];