const products = [
    {   id: 1,
        name: 'Producto 1',
        price: 100,
        description: 'Descripcion del producto 1',
        image: 'https://',
        category: 'Categoria 1',
        stock: 10
    },
    {   id: 2,
        name: 'Producto 2',
        price: 200,
        description: 'Descripcion del producto 2',
        image: 'https://',
        category: 'Categoria 2',
        stock: 20
    },
    {   id: 3,
        name: 'Producto 3',
        price: 300,
        description: 'Descripcion del producto 3',
        image: 'https://',
        category: 'Categoria 3',
        stock: 30
    },
    {   id: 4,
        name: 'Producto 4',
        price: 400,
        description: 'Descripcion del producto 4',
        image: 'https://',
        category: 'Categoria 4',
        stock: 40
    },
    {   id: 5,
        name: 'Producto 5',
        price: 500,
        description: 'Descripcion del producto 5',
        image: 'https://',
        category: 'Categoria 5',
        stock: 50
    },
    {   id: 6,
        name: 'Producto 6',
        price: 600,
        description: 'Descripcion del producto 6',
        image: 'https://',
        category: 'Categoria 6',
        stock: 60
    },
    {   id: 7,
        name: 'Producto 7',
        price: 700,
        description: 'Descripcion del producto 7',
        image: 'https://',
        category: 'Categoria 7',
        stock: 70
    },
    {   id: 8,
        name: 'Producto 8',
        price: 800,
        description: 'Descripcion del producto 8',
        image: 'https://',
        category: 'Categoria 8',
        stock: 80
    },
    {   id: 9,
        name: 'Producto 9',
        price: 900,
        description: 'Descripcion del producto 9',
        image: 'https://',
        category: 'Categoria 9',
        stock: 90
    },
    {   id: 10,
        name: 'Producto 10',
        price: 1000,
        description: 'Descripcion del producto 10',
        image: 'https://',
        category: 'Categoria 10',
        stock: 100
    }
];